# Generated by Django 3.1.4 on 2021-03-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('product_img', models.ImageField(upload_to='productimg/', verbose_name='Изображение товара')),
                ('product_purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Закупочная цена')),
                ('product_old_price', models.IntegerField(verbose_name='Старая цена')),
                ('product_discount', models.IntegerField(verbose_name='Скидка (%)')),
                ('product_copy', models.SmallIntegerField(verbose_name='Количество')),
                ('product_country', models.CharField(choices=[(None, 'Страна'), ('RU', 'Россия'), ('KR', 'Корея'), ('FR', 'Франция'), ('QA', 'Катар'), ('IN', 'Индия'), ('CN', 'Китай'), ('IT', 'Италия'), ('EG', 'Египет'), ('VN', 'Вьетнам'), ('AE', 'ОАЭ')], max_length=2, verbose_name='Страна')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_short_description', models.TextField(verbose_name='Краткое описание')),
                ('product_category', models.CharField(choices=[(None, 'Категория'), ('a', 'Арабская'), ('b', 'Корейская'), ('c', 'Аюрведа')], max_length=1, verbose_name='Категория')),
                ('product_slug', models.SlugField(max_length=200)),
                ('product_available', models.BooleanField(default=True)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'index_together': {('id', 'product_slug')},
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_img', models.ImageField(upload_to='sliderimg/')),
                ('cms_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('cms_text', models.CharField(max_length=200, verbose_name='Текст')),
                ('cms_css', models.CharField(default='-', max_length=200, verbose_name='CSS класс')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('review_dt', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
