# Generated by Django 3.1.4 on 2021-03-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_order',
        ),
    ]
