# Generated by Django 3.1.4 on 2021-03-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210322_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='cms_css',
            new_name='css',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='cms_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='cms_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='cms_img',
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to='sliderimg/', verbose_name='Изображение'),
        ),
    ]
