# Generated by Django 3.1.4 on 2021-03-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentcrm',
            name='coment_bind',
        ),
        migrations.DeleteModel(
            name='OrderUser',
        ),
        migrations.DeleteModel(
            name='StatusCrm',
        ),
        migrations.DeleteModel(
            name='ComentCrm',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
