# Generated by Django 3.1.4 on 2021-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telefon',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
