# Generated by Django 3.1.4 on 2021-03-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_telefon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='telefon',
            new_name='phone',
        ),
    ]
